### ISSUE TITLE
Live Run

### ISSUE THREAD

**Issue by Mzajkhost** [xe-nvdk/crowd-counting#1]
Hello ,
can you show me how to setup the code for live cam ?
and how to run it

**Comment by xe-nvdk** [comment]
Hello. The code to use in live cam is this one: https://github.com/xe-nvdk/crowd-counter/blob/main/live.py

You need to execute running python3 live.py. Make sure to have the modules that you need. CV2, influxdb_client. Create an InfluxDB Cloud Account here: https://cloud2.influxdata.com/signup?source=ignacio

**Comment by Mzajkhost** [comment]
Thanks, i did and install all of it ,and created account but where can i add my camera info , can you make video how to setup it

**Comment by xe-nvdk** [comment]
No need to add anything to the file. By default is going to capture your webcam o the video device that you have connected.

**Comment by Mzajkhost** [comment]
Thanks for your response, the cam i have has a real ip connected to internet

**Comment by xe-nvdk** [comment]
Oh, I know what you're doing. In that case, as is, this script isn't useful. You need to see if you can add a module to feed through an IP camera. I never tried, but I will take a look at what's required.

**Comment by xe-nvdk** [comment]
I'm seeing that isn't hard at all, you need to take the live.py file and change the variable cap...

`cap = cv2.VideoCapture("http://192.168.18.37:8090/test.mjpeg")`

try it and let me know.

**Comment by xe-nvdk** [comment]
I just added an example: https://github.com/xe-nvdk/crowd-counter/commit/a969d067f6b164253e039fc6685e88ec34e924c1

**Comment by Mzajkhost** [comment]
thanks 
i run it and i get

PS D:\crowd-counter-main> py live2.py
Traceback (most recent call last):
  File "D:\crowd-counter-main\live2.py", line 45, in <module>
    write_api.write(bucket=bucket, record=p)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\client\write_api.py", line 254, in write
    results = list(map(write_payload, payloads.items()))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\client\write_api.py", line 252, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\client\write_api.py", line 380, in _post_write
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\service\write_service.py", line 64, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\service\write_service.py", line 168, in post_write_with_http_info
    return self.api_client.call_api(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\api_client.py", line 170, in __call_api
    response_data = self.request(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\api_client.py", line 385, in request
    return self.rest_client.POST(url,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\rest.py", line 301, in POST
    return self.request("POST", url,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\influxdb_client\rest.py", line 251, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 05 Jul 2021 05:08:12 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '67', 'Connection': 'keep-alive', 'trace-id': '9755407c4a49a0c2', 'trace-sampled': 'false', 'x-platform-error-code': 'not found', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'})
HTTP response body: {"code":"not found","message":"bucket \"crowd-counter\" not found"}

**Comment by xe-nvdk** [comment]
Have you created the bucket in InfluxDB Cloud? Have you set the configuration in the file ini?

https://docs.influxdata.com/influxdb/cloud/organizations/buckets/create-bucket/

**Comment by Mzajkhost** [comment]
Yes i add the configuration to ini , and create bucket but i think there issue in db

**Comment by xe-nvdk** [comment]
What's the name of the DB (bucket) that you created? 

Must be crowd-counter or you need to change to the correct bucket name.

**Comment by Mzajkhost** [comment]
I renamed it but what data should i add in it

**Comment by Mzajkhost** [comment]
sir it worked and run the video and cam but its not counting and get this '
  File "D:\crowd-counter-main\live2.py", line 32, in <module>
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1hfhc_rd\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
